permissionDemo/src/main/java/be/c4j/demo/security/demo/model/Department.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.model;

import java.io.Serializable;

/**
 * This is an entity object in production type application
 */
public class Department implements Serializable {

    private Long id;
    private String name;
    private Employee manager;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Employee getManager() {
        return manager;
    }

    public void setManager(Employee manager) {
        this.manager = manager;
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/model/Employee.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.model;

import java.util.Date;

/**
 * This is an entity object in production type application
 */
public class Employee {

    private Long id;
    private String name;
    private Date hireDate;
    private double salary;
    private Employee manager;
    private Department department;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getHireDate() {
        return hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    public Employee getManager() {
        return manager;
    }

    public void setManager(Employee manager) {
        this.manager = manager;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Employee employee = (Employee) o;

        if (!hireDate.equals(employee.hireDate)) {
            return false;
        }
        if (!name.equals(employee.name)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + hireDate.hashCode();
        return result;
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/model/HRAppPermission.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.model;

import be.c4j.ee.security.permission.NamedPermission;

/**
 * This is an entity object in production type application
 */
public class HRAppPermission implements NamedPermission {

    private String name;
    private String domain;
    private String actions;
    private String target;

    public HRAppPermission(String name, String domain, String actions, String target) {
        this.name = name;
        this.domain = domain;
        this.actions = actions;
        this.target = target;
    }

    public String getName() {
        return name;
    }

    @Override
    public String name() {
        return getName();
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getActions() {
        return actions;
    }

    public void setActions(String actions) {
        this.actions = actions;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getDomainPermissionRepresentation() {
        StringBuilder result = new StringBuilder();
        result.append(domain).append(':').append(actions).append(':').append(target);
        return result.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        HRAppPermission that = (HRAppPermission) o;

        if (!name.equals(that.name)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return name.hashCode();
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/model/Principal.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.model;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * This is an entity object in production type application
 */
public class Principal {

    private UUID id = UUID.randomUUID();
    private Employee employee;
    private String userName;
    private String password;
    private Set<HRAppPermission> permissions = new HashSet<HRAppPermission>();

    public UUID getId() {
        return id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Set<HRAppPermission> getPermissions() {
        return permissions;
    }

    public void addPermission(HRAppPermission permission) {
        permissions.add(permission);
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/model/dto/DepartmentWithSalaryTotal.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.model.dto;

import be.c4j.demo.security.demo.model.Department;

/**
 *
 */
public class DepartmentWithSalaryTotal extends Department {

    private double salaryTotal;

    public DepartmentWithSalaryTotal(Department department, double salaryTotal) {
        setId(department.getId());
        setName(department.getName());
        setManager(department.getManager());
        this.salaryTotal = salaryTotal;
    }

    public double getSalaryTotal() {
        return salaryTotal;
    }

    public void setSalaryTotal(double salaryTotal) {
        this.salaryTotal = salaryTotal;
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/view/DepartmentBean.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.view;

import be.c4j.demo.security.demo.model.Employee;
import be.c4j.demo.security.demo.model.dto.DepartmentWithSalaryTotal;
import be.c4j.demo.security.demo.service.DepartmentService;
import be.c4j.demo.security.demo.service.EmployeeService;
import org.apache.deltaspike.core.api.provider.BeanProvider;
import org.apache.deltaspike.core.api.scope.ViewAccessScoped;

import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.List;

/**
 *
 */
@ViewAccessScoped
@Named
public class DepartmentBean implements Serializable {

    @Inject
    private transient DepartmentService departmentService;

    @Inject
    private transient EmployeeService employeeService;

    private List<DepartmentWithSalaryTotal> allDepartments;

    private Long departmentId;
    private List<Employee> employeesOfDepartment;

    public List<DepartmentWithSalaryTotal> getAllDepartments() {
        if (allDepartments == null) {
            allDepartments = departmentService.getAllDepartments();
        }
        return allDepartments;
    }

    public Long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public List<Employee> getEmployeesOfDepartment() {
        return employeesOfDepartment;
    }

    public void loadEmployees() {
        employeesOfDepartment = employeeService.getEmployeesOfDepartment(departmentId);
    }

    /*
         * Manual initialization is required after deserialization.  departmentService is not serializable
         * so this can solve the problem.
         */
    private void readObject(ObjectInputStream in)
            throws IOException, ClassNotFoundException {
        in.defaultReadObject();
        departmentService = BeanProvider.getContextualReference(DepartmentService.class);
        employeeService = BeanProvider.getContextualReference(EmployeeService.class);
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/view/DepartmentCreateBean.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.view;

import be.c4j.demo.security.demo.service.DepartmentService;

import javax.enterprise.inject.Model;
import javax.inject.Inject;

/**
 *
 */
@Model
public class DepartmentCreateBean {

    @Inject
    private DepartmentService departmentService;

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void saveDepartment() {
        departmentService.createDepartment(name);
    }
}

permissionDemo/src/main/java/be/c4j/demo/security/demo/view/EmployeeBean.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.view;

import be.c4j.demo.security.demo.model.Employee;
import be.c4j.demo.security.demo.service.EmployeeService;
import be.c4j.ee.security.model.UserPrincipal;
import org.apache.deltaspike.core.api.provider.BeanProvider;
import org.apache.deltaspike.core.api.scope.ViewAccessScoped;

import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.Map;

/**
 *
 */
@Named
@ViewAccessScoped
public class EmployeeBean implements Serializable {

    @Inject
    private transient UserPrincipal principal;

    @Inject
    private transient EmployeeService employeeService;

    private Long employeeId;

    private Employee employee = new Employee();

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    private boolean youMarkerFound() {
        Map<String, String> requestParameterMap = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap();
        return requestParameterMap.containsKey("you");
    }

    public void loadEmployee() {
        if (youMarkerFound()) {
            employeeId = null;
        }
        if (employeeId == null) {

            employee = employeeService.getEmployee(principal);
        } else {
            if (!employeeId.equals(employee.getId())) {
                employee = employeeService.getEmployee(employeeId);
            }
        }

    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public void saveSalary() {
        // employeeId is also filled by using f:param within p:commandButton.
        employee.setId(employeeId);
        employeeService.updateSalary(employee);
    }

    /*
     * Manual initialization is required after deserialization.  departmentService is not serializable
     * so this can solve the problem.
     */
    private void readObject(ObjectInputStream in)
            throws IOException, ClassNotFoundException {
        in.defaultReadObject();
        // FIXME principal =
        employeeService = BeanProvider.getContextualReference(EmployeeService.class);
    }

}

permissionDemo/src/main/java/be/c4j/demo/security/demo/view/InfoBean.java
/*
 * Copyright 2014-2017 Rudy De Busscher (www.c4j.be)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.c4j.demo.security.demo.view;

import be.c4j.demo.security.demo.model.dto.UserWithPermission;
import be.c4j.demo.security.demo.service.InMemoryDatabase;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

/**
 *
 */
@ApplicationScoped
@Named
public class InfoBean {

    @Inject
    private InMemoryDatabase database;

    public List<UserWithPermission> getUsers() {
        return database.getAvailableUsersWithInfo();
    }
}

permissionDemo/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2014-2017 Rudy De Busscher (www.c4j.be)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:sec="http://www.c4j.be/secure">
<ui:composition template="/WEB-INF/templates/template.xhtml">

    <ui:define name="title">Octopus Permission demo</ui:define>

    <ui:define name="body">

        <p:panel header="Welcome">
            Example application demonstrating the permission based features of Octopus. <br/>
            TODO refer to the more elaborated explanation in the Hands-On-Lab
        </p:panel>

        <h:panelGroup>
            Since you are not authenticated yet, navigating to one of the pages will show a login form.
            <sec:requiresUser not="true"/>
        </h:panelGroup>


    </ui:define>
</ui:composition>
</html>

permissionDemo/src/main/webapp/login.xhtml
<!--

    Copyright 2014-2017 Rudy De Busscher (www.c4j.be)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <h:outputStylesheet library="css" name="starter.css"/>
</h:head>
<h:body>
    <h2>Login</h2>
    <h:form id="login">
        <h:panelGrid columns="2">
            <p:outputLabel for="username" value="User name:"/>
            <p:inputText id="username" value="#{loginBean.username}" required="true"/>

            <p:outputLabel for="password" value="Password:"/>
            <p:password id="password" value="#{loginBean.password}" required="true" feedback=""/>

            <h:panelGroup/>
            <p:commandButton value="Login" actionListener="#{loginBean.doLogin}"/>

        </h:panelGrid>
        <p:messages globalOnly="true" layout="table" autoUpdate="true"/>
    </h:form>
    In below table you can find the valid user names. The pasword is the reverse of the user name. User name and password are case sensitive.
    <p:dataTable value="#{infoBean.users}" var="user">
        <p:column headerText="User name">
            #{user.userName}
        </p:column>
        <p:column headerText="Employee name">
            #{user.name}
        </p:column>
        <p:column headerText="Permission">
            #{user.permissionInfo}
        </p:column> </p:dataTable>
</h:body>
</html>

permissionDemo/src/main/webapp/unauthorized.xhtml
<!--

    Copyright 2014-2017 Rudy De Busscher (www.c4j.be)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head>

</h:head>
<h:body>
    <h1> Unauthorized exception</h1>
    <p:messages/>
    Location : <br/>
    <h:outputText value="#{flash.interceptionInfo}" escape="false"/>
</h:body>
</html>